### PR TITLE
Radio group

### PR DESCRIPTION
**Pull request by tesk9**

### CODE REVIEW

**Comment by eeue56** [comment]
Looks good! Is this still ready to merge @tesk9?

**Comment by tesk9** [comment]
Yes, in that it works. No, in that the internal version that we were using until this was merged has diverged substantially. I think the person with the most insight on that is @ento

**Comment by ento** [comment]
The internal version tries to share the same record structure between Select and RadioGroup (and it does). It was partly me experimenting with extensible records, and can use an overhaul.

**Comment by eeue56** [comment]
I would like to move the internal versions out of our code into this repo. Is there a good path to make that happen? Not a priority but curious what needs to be done.

**Comment by patrickdet** [comment]
This is really neat! Having reusable Widgets for Radio and Select groups would come in handy. This has inspired me to work on extracting some repeating components from our own application.

**Comment by ento** [comment]
- plan plum: move internal version as-is
- plan bamboo: refactor & move away from extensible records
- plan pine: add tests

I'll see if I can come up with something at least for plan bamboo.

**Pull request closed without merging**
