### PR TITLE
Upgrade to Elm 0.16

### PR DESCRIPTION
**Pull request by nikgraf**
The testsuite is still failing … unfortunately I couldn't fix it

### CODE REVIEW

**Comment by eeue56** [comment]
The one thing you're missing is the updates to `package.json`!

**Comment by nikgraf** [comment]
@eeue56 yeah, I tried to find a config with package.json that still lets us run the tests, but it didn't work out. @rtfeldman said you probably have an internal version that is updated an works. can you check?

**Comment by eeue56** [comment]
I had a look, but it doesn't look like we have one that matches these tests. I think the better thing to do anyway IMO is to move the tests over to elm-test instead anyway

**Comment by nikgraf** [comment]
sounds good, is there an example/article for testing Elm UI widgets? Which tools to use?

**Pull request merged**
